version: "3.9"

services:
 postgres_db:
  container_name: postgres
  image: postgres:latest
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: 2002
   POSTGRES_DB: demoapp
  ports:
  - "5432:5432"
  networks:
   - deploy-guide-dev
  volumes:
  - postgres-data:/var/lib/postgresql/data
 app:
  container_name: deploy-guide
  build:
   context: .
   dockerfile: Dockerfile
  #environment:
  #  - DB_POST=5433
  #  - DB_HOST=postgres_db
  #  - DB_USER=postgres
  #  - DB_PASSWORD=2002
  #  - DB_NAME=postgres
    
  ports:
   - "8081:80"
  networks:
   - deploy-guide-dev
  depends_on:
   - postgres_db
 
networks:
 deploy-guide-dev:
  driver: bridge
volumes:
 postgres-data:
  